webapi:
    build:
      context: .
      dockerfile: Kdbapp/Dockerfile
    container_name: kdb-app-container
    restart: always
    ports:
      - "8968:8080"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Формат 1 (Стандартный для Docker + .NET)
      - "ConnectionStrings__DefaultConnection=Server=postgres-db;Port=5432;Database=kbrddbapp;User Id=postgres;Password=TZzGdgtJGBfky99We9hu26lvIgWGi11RrWXK70zo4EW9dXQpmCizY6zwaAieR6wj;"
      # Формат 2 (Альтернативный, на случай если Coolify съедает двойное подчеркивание)
      - "ConnectionStrings:DefaultConnection=Server=postgres-db;Port=5432;Database=kbrddbapp;User Id=postgres;Password=TZzGdgtJGBfky99We9hu26lvIgWGi11RrWXK70zo4EW9dXQpmCizY6zwaAieR6wj;"