version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Kdbapp/Dockerfile
    container_name: kdb-backend
    restart: always
    ports:
      - "8968:5237"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5237
      # ВНИМАНИЕ: Изменил Port на 8967, как ты указал для базы данных
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=8967;Database=kbrddbapp;Username=postgres;Password=8585
    extra_hosts:
      - "host.docker.internal:host-gateway"