version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: kdb-postgres-container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Kdbapp/Dockerfile
    container_name: kdb-app-container
    restart: always
    ports:
      - "8968:8080"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__Key=${Jwt__Key}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}

volumes:
  pgdata: