services:
  backend:
    build:
      context: ..                 # Корень репозитория: тут лежит .dockerignore, а Dockerfile ждёт путь Kdbapp/Kdbapp.csproj
      dockerfile: Kdbapp/Dockerfile
      network: host               # Решает проблему, если контейнер во время сборки не видит интернет/NuGet
    container_name: kdb-backend
    restart: always
    ports:
      - "8968:5237"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5237
      - ConnectionStrings__DefaultConnection=Host=89.109.16.50;Port=8967;Database=postgres;Username=postgres;Password=TZzGdgtJGBfky99We9hu26lvIgWGi11RrWXK70zo4EW9dXQpmCizY6zwaAieR6wj
